# Generated by Django 3.2.5 on 2021-07-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='message',
        ),
    ]
