# Generated by Django 3.2.5 on 2021-08-01 00:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechat',
            name='users',
        ),
        migrations.AddField(
            model_name='privatechat',
            name='users',
            field=models.ManyToManyField(related_name='chat_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
