# Generated by Django 3.2.5 on 2021-07-30 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_groupchat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_message', to='chat.groupchat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat_private',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_message', to='chat.privatechat'),
        ),
    ]
