# Generated by Django 3.2.5 on 2021-07-30 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210730_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_message', to='chat.groupchat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat_private',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_message', to='chat.privatechat'),
        ),
    ]
