# Generated by Django 3.2.5 on 2021-08-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210801_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
